apps/www/app/docs/layout.tsx
the issue is related to [using `1fr`](https://stackoverflow.com/questions/52861086/why-does-minmax0-1fr-work-for-long-elements-while-1fr-doesnt)
=> fix(#7): always prefer `minmax(0, 1fr)` instead of `1fr`

apps/www/app/layout.tsx, apps/www/components/fonts.tsx, templates/next-template/pages/_app.tsx
We should use `display: 'swap'` because Inter font does not load on hard reload and (sometimes) on the first visit to the site. Do a hard reload and reload to see the difference.
=> fix: add `display: 'swap'` for fonts

templates/next-template/components/ui/tooltip.tsx
The user would instead put the provider in `_app.tsx` for example
This also allows user to pass props to the provider like in [radix-ui example](https://www.radix-ui.com/docs/primitives/components/tooltip#examples)
`<TooltipProvider delayDuration={500} skipDelayDuration={500}>`
=> avoid creating new tooltip provider for every tooltip

apps/www/components/ui/switch.tsx
This is a bug fix for the issue https://github.com/shadcn/ui/issues/24
The switch position change on some screen sizes or in some zoom percent.
I solve that by putting the **items-center** on in this part of **switch.tsx** ui component.
```tsx
<SwitchPrimitives.Root
className={cn(
"peer inline-flex items-center h-[24px] w-[44px] shrink-0 ....",
className
)}
{...props}
ref={ref}
>
```
=> fix: switch position issue

apps/www/components/ui/tabs.tsx
Fixes https://github.com/shadcn/ui/issues/42
=> Fix: Issue 42: Use light text in TabsPrimitive.Trigger when dark mode

apps/www/components/ui/slider.tsx, templates/next-template/components/ui/slider.tsx
for some reason we were extracting the value prop from props but not passing it to the slider root.
fixed it by not extracting it from props, so its passed automatically.
=> fix(slider): value prop not being passed

package.json
Husky is not installed automatically, I noticed this when I am trying to commit to my fork.
adding prepare script should work, see [reference](https://typicode.github.io/husky/#/?id=install)
also, you might want to re-run prettier. I think the pre-commit hook didn't run for some contributors
Here's the changes after I run it, let me know if you want me to push the prettier run commit 😃
=> chore: add husky prepare

apps/www/content/docs/primitives/toast.mdx
The destructive toast component example used the wrong example src
=> fix(docs): fix destructive toast example src

apps/www/components/command-menu.tsx
prevent the default action of the browser in order to open the command menu.
https://user-images.githubusercontent.com/70624701/219858176-824cfc1b-c114-4d32-bd29-2d60fee5adbd.mp4
=> fix(www/command-menu): command menu keybinding not working

templates/next-template/pages/_app.tsx
An extra curly brace was hiding at the end of the style tag.
=> fix: remove extra curly brace in style tag

apps/www/content/docs/primitives/scroll-area.mdx
Just noticed the description on https://ui.shadcn.com/docs/primitives/scroll-area was wrong, and duplicated from https://ui.shadcn.com/docs/primitives/separator.
This PR fixes that and updates the description to be the same as https://www.radix-ui.com/docs/primitives/components/scroll-area.
Thank you for these components 🙂
=> Fix description in `scroll-area.mdx`

apps/www/content/docs/primitives/dialog.mdx
Just found what I'm guessing is another copy/paste mistake (see #136), this time on https://ui.shadcn.com/docs/primitives/dialog. It's the same as https://ui.shadcn.com/docs/primitives/alert-dialog.
This PR updates this description to the one found on https://www.radix-ui.com/docs/primitives/components/dialog.
=> Fix description in `dialog.mdx`

apps/www/app/layout.tsx, apps/www/components/fonts.tsx, apps/www/package.json
This is not a necessary change as of now, but good to have, I just encountered it while using it, so thought of doing it
Issue #144
=> Replacing third party @next/font with Next.js inbuilt next/font

apps/www/content/docs/installation.mdx
Add `type` keyword because Typescript complains, since ClassValue is only imported as a type.
=> Add type keyword to ClassValue

apps/www/app/examples/cards/components/date-picker.tsx, apps/www/app/sink/page.tsx, apps/www/components/component-example.tsx, apps/www/components/copy-button.tsx, apps/www/components/examples/combobox/demo.tsx, apps/www/components/examples/combobox/dropdown-menu.tsx, apps/www/components/examples/combobox/popover.tsx, apps/www/components/examples/date-picker/demo.tsx, apps/www/components/examples/date-picker/with-presets.tsx, apps/www/components/examples/date-picker/with-range.tsx, apps/www/components/examples/index.tsx, apps/www/components/mdx-components.tsx, apps/www/config/docs.ts, apps/www/content/docs/components/calendar.mdx, apps/www/content/docs/components/combobox.mdx, apps/www/content/docs/components/command.mdx, apps/www/content/docs/components/date-picker.mdx
=> docs: move combobox and date picker to their own page

apps/www/app/examples/tasks/components/data-table-toolbar.tsx, apps/www/components/examples/data-table/data-table.tsx, apps/www/content/docs/components/data-table.mdx
Add empty string as fallback if value is undefined or null to prevent error.
Fixes #336
=> fix: uncontrolled input error on data-table

apps/www/components/code-block-wrapper.tsx
Just a missing bracket in a tailwind custom value class
=> fix(code-block-wrapper): missing ']' in className

apps/www/content/docs/forms/react-hook-form.mdx
This PR adds the "@radix-ui/react-slot" dependency to the FormField component. This addition is meant to streamline the DX and align it with the existing standards in the Button component.
The following text has been changed, from:
```
npm install react-hook-form zod @hookform/resolvers
```
to:
```
npm install react-hook-form zod @hookform/resolvers @radix-ui/react-slot
```
It's important to note that the "@radix-ui/react-slot" dependency is already being utilized in the Button component. However, the current [next-template](https://github.com/shadcn/next-template) still uses an older version without "@radix-ui/react-slot" implementation. 
Given that the installation guide for the Button component recommends installing "@radix-ui/react-slot", it seems fitting to include this in the …
=> Adding @radix-ui/react-slot Dependency to FormField Component in react-hook-form.mdx

apps/www/components/ui/radio-group.tsx
In this PR, I've added the TailwindCSS class "aspect-square" to the RadioGroupItem component in `apps/www/components/ui/radio-group.tsx`. This change enhances the visual consistency of radio buttons across different device sizes and widths.
Here's a snippet of the code change:
**From:**
```tsx
className={cn(
"h-4 w-4 rounded-full border border-primary text-primary ring-offset-background focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
className
)}
```
**To:**
```tsx
className={cn(
"aspect-square h-4 w-4 rounded-full border border-primary text-primary ring-offset-background focus:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed …
```
=> fix: Adding "aspect-square" class to RadioGroupItem Component

apps/www/app/examples/forms/account/account-form.tsx
Fixed the language placeholder and the empty text when search and doesn't found a language.
Search placeholder:
Empty text:
=> fix(www): fix language placeholder on forms example

packages/cli/package.json, packages/cli/src/index.ts, packages/cli/src/utils/get-components.ts, packages/cli/src/utils/get-project-info.ts, pnpm-lock.yaml
This pr adds:
- usage of the commonly used environment variable https_proxy. This allows fetch to work behind a proxy.
- when installing a component the cli now resorts to either `./src/components/ui` or `./components/ui` depending on which directory already exists (e.g.: from previous installations)
=> feat(cli): use https_proxy and consider previous install locations

apps/www/components/tailwind-indicator.tsx, templates/next-template/components/tailwind-indicator.tsx
Since the breakpoint prefixes work on a `min-width` basis, it's only necessary to specify the _following_ breakpoint with `:hidden`.
=> fix: remove unnecessary tailwind-indicator classnames

apps/www/public/schema.json
=> include `new-york` in schema.json

packages/cli/src/index.ts
This PR enhances the code by removing the unused `PROJECT_DEPENDENCIES` variable from the `cli/src/index.ts` file. The variable is already defined and used in the `cli/src/commands/init.ts` file, so there is no need for redundant declarations.
```diff
- const PROJECT_DEPENDENCIES = [
-   "tailwindcss-animate",
-   "class-variance-authority",
-   "clsx",
-   "tailwind-merge",
- ]
```
=> Remove unused `PROJECT_DEPENDENCIES` variable

.changeset/fast-shoes-wash.md, apps/www/content/docs/components/toast.mdx, packages/cli/src/utils/transformers/transform-css-vars.ts, packages/cli/test/utils/apply-color-mapping.test.ts
=> fix(cli): use slash for alpha values in colors

apps/www/app/examples/tasks/components/data-table-toolbar.tsx
This just edits the example for data-table-toolbar. I have not checked if any docs need updating that reference this method of checking for isFiltered
If you select all filters that equals all rows we never display the reset button. 
We can get the state of selected columnFilters and if there is any selected display the reset button.
=> Update data-table-toolbar to correctly handle isFiltered

apps/www/content/docs/installation/gatsby.mdx
Hi!
Gatsby maintainer here 👋 I stumbled upon the Gatsby guide and have some suggestions for improvements. Comments are inlined in the PR
=> docs(www): Improve Gatsby guide

apps/www/content/docs/installation/astro.mdx
Hi, 
just started using the project in astro and went through the installation guide. By default, the `@astrojs/tailwind` integration includes the tailwind base styles (@tailwind base; @tailwind components; @tailwind utilities;) since we need a custom CSS file to adjust colors and stuff they are included twice in the build. 
We can tell astro to not `applyBaseStyles` because we do that on our own.
See docs for `@astrojs/tailwind`: https://docs.astro.build/en/guides/integrations-guide/tailwind/#applybasestyles
I updated the astro setup guide to add an additional step to set the options in `astro.config.mjs`
=> docs(www): improve astro guide

apps/www/content/docs/cli.mdx
Typescript question was missing from the CLI docs (it is present on installation guides already).
=> docs: add typescript configuration question to cli docs

apps/www/app/examples/forms/account/account-form.tsx, apps/www/registry/default/example/combobox-form.tsx, apps/www/registry/new-york/example/combobox-form.tsx
**Description:**
- The search in the `Combobox` for languages is done by language value instead of label.
- https://ui.shadcn.com/docs/components/combobox#form
- https://ui.shadcn.com/examples/forms/account
**Related Issues:**
- #933 
- #1072 
**Video:**
https://github.com/shadcn-ui/ui/assets/24194621/0cac67f9-01c1-4fc2-b906-7ad83c60e3df
closes #933, closes #1072
=> fix(combobox): search language by label in examples

apps/www/content/docs/components/aspect-ratio.mdx, apps/www/content/docs/components/form.mdx
This PR:
- Fixes #967 
- Fixes #687 (only form docs)
- Fixes typo in aspect-ratio alt prop
=> fix(docs): missing form manual installation and aspect-ratio typo

apps/www/content/docs/components/toast.mdx, apps/www/lib/rehype-component.ts
This PR:
- Fixes #780 
- Fixes #687 (only toast docs)
=> fix(docs): add missing files in toast manual installation and data-table

.changeset/new-jeans-doubt.md, packages/cli/test/commands/init.test.ts
Removed duplicate calls in init.test.
Noticed it while doing #1292
=> chore: remove a duplicate call in init.test

apps/www/app/examples/tasks/components/data-table-faceted-filter.tsx
VSCode is shouting at me for this identical interface and function name:
This PR just renames the interface to a more sensible one.
=> fix: identical interface and function name

apps/www/content/docs/dark-mode/next.mdx
The ThemeProvider is missing disableTransitionOnChange prop. Adding this prop ensures your UI to stay consistent when changing the theme.
=> docs(dark-mode): add missing prop to ThemeProvider

.changeset/proud-items-join.md, apps/www/components/copy-button.tsx, apps/www/components/mdx-components.tsx, apps/www/lib/rehype-npm-command.ts, apps/www/types/unist.ts
The title basically says it all
adding a component:
creating an app:
initing shadcn-ui:
=> feat(www): add bun support for installation commands

apps/www/registry/default/example/combobox-form.tsx
At the language example of combobox, `framework` work is used instead of `language`. This PR fixes that small issue
=> docs: language example - remove copy-pasted text artifacts

apps/www/styles/globals.css
The default destructive button is failing contrast ratio for WCAG AA standards. 
This substitutes the previous HSL equivalent of `red-500` to `red-600`. This was previous done in another PR: https://github.com/shadcn-ui/ui/pull/79 which looks like it was incorrectly translated to the CSS Variable setup with HSL.
=> fix(a11y): destructive contrast increase

apps/www/config/docs.ts, apps/www/content/docs/dark-mode/index.mdx, apps/www/content/docs/dark-mode/remix.mdx
I added documentation to support dark mode for Remix.
- remix-themes is required
https://github.com/shadcn-ui/ui/assets/48875246/457f8e99-24e1-479e-bbdc-88048d58502f
=> docs(www): add remix dark mode docs

apps/www/registry/default/ui/switch.tsx, apps/www/registry/new-york/ui/switch.tsx
If you use `px` when the base font size is not `16px`, the `Thumb` transform goes into wrong
=> fix(switch): change width unit to rem

apps/www/content/docs/installation/next.mdx
Added missing import statement in fonts example in Next.js installation docs
=> docs(www): Missing import statement

apps/www/app/examples/music/components/menu.tsx
Fixed typo from 'Famliy' to 'Family' in music example.
=> docs(www): Fix typo

apps/www/content/docs/components/resizable.mdx
This pull request updates the documentation to reflect the correct component name, changing `ResizableGroup` to `ResizablePanelGroup`. This change ensures consistency and correctness in the documentation, aiding developers in correctly implementing the component.
- In the code examples within the documentation, `ResizableGroup` has been renamed to `ResizablePanelGroup`.
- This change is applied to both horizontal and vertical orientation examples.
- These changes are confined to documentation and do not alter the actual implementation or functionality of the components in question.
Please review the changes for accuracy and merge if appropriate. Thanks!
=> Update: Rename 'ResizableGroup' to 'ResizablePanelGroup' in Documentation

apps/www/content/docs/components/drawer.mdx
=> docs(drawer): missing drawer footer import in drawer usage example

apps/www/content/docs/components/pagination.mdx
=> docs(pagination): wrong import path of components in pagination usage

apps/www/components/mobile-nav.tsx
- Update the `mobile-nav` component and added `new` label if `item.label` is present in the `docsConfig.sidebarNav`.
=> Added new label for mobile navigation

.changeset/odd-pigs-cross.md, apps/www/content/docs/components-json.mdx, apps/www/public/schema.json, packages/cli/src/utils/get-config.ts, packages/cli/src/utils/registry/index.ts, packages/cli/src/utils/transformers/transform-import.ts, packages/cli/test/fixtures/config-ui/components.json, packages/cli/test/fixtures/config-ui/package.json, packages/cli/test/fixtures/config-ui/tsconfig.json, packages/cli/test/utils/__snapshots__/transform-import.test.ts.snap, packages/cli/test/utils/get-config.test.ts, packages/cli/test/utils/get-item-target-path.test.ts, packages/cli/test/utils/transform-import.test.ts
This PR adds support for custom dir/path for ui components. It builds on top of the existing schema, `aliases` and `resolveImport`.
This will place components inside `.[ROOT]/components/ui`.
```json
{
"$schema": "https://ui.shadcn.com/schema.json",
"aliases": {
"components": "@/components",
"utils": "@/lib/utils",
}
}
```
This will place components inside `.[ROOT]/primitives`. Imports will be resolved automatically.
```json
{
"$schema": "https://ui.shadcn.com/schema.json",
"aliases": {
"components": "@/components",
"utils": "@/lib/utils",
"ui": "@/primitives" <---- adds components to `.[ROOT]/primitives`👈
}
}
```
```json
{
"$schema": "https://ui.shadcn.com/schema.json",
"aliases": {
"components": "~/components",
"utils": "~/lib/utils",
"ui": "~/app/ui" <---- adds components to …
```
=> feat(cli): add support for custom ui dir

apps/www/content/docs/components/resizable.mdx
In the [resizable documentation](https://ui.shadcn.com/docs/components/resizable) the handle example shows a horizontal handle but the code example has `direction="vertical"` when it should be `direction="horizontal"`
=> fix(docs): Resizable panel direction should be horizontal

apps/www/registry/default/example/toggle-demo.tsx, apps/www/registry/default/example/toggle-disabled.tsx, apps/www/registry/default/example/toggle-group-demo.tsx, apps/www/registry/default/example/toggle-group-disabled.tsx, apps/www/registry/default/example/toggle-group-lg.tsx, apps/www/registry/default/example/toggle-group-outline.tsx, apps/www/registry/default/example/toggle-group-single.tsx, apps/www/registry/default/example/toggle-group-sm.tsx
- some `Toggle` and `ToggleGroup` demos had incorrect `aria-label` or `value` props
=> fix(www): incorrect toggle aria labels and values

apps/www/content/docs/components/carousel.mdx
before fix: "@/registry/new-york/ui/carousel"
after fix: "@/components/ui/carousel"
this is ease the user to copy paste without error
=> fix: typo on carousel import

apps/www/app/examples/forms/account/account-form.tsx, apps/www/app/examples/forms/appearance/appearance-form.tsx, apps/www/app/examples/forms/display/display-form.tsx, apps/www/app/examples/forms/notifications/notifications-form.tsx, apps/www/app/examples/forms/profile-form.tsx, apps/www/content/docs/components/form.mdx, apps/www/lib/validations/log.ts, apps/www/lib/validations/og.ts, apps/www/registry/default/example/calendar-form.tsx, apps/www/registry/default/example/calendar-react-hook-form.tsx, apps/www/registry/default/example/checkbox-form-multiple.tsx, apps/www/registry/default/example/checkbox-form-single.tsx, apps/www/registry/default/example/combobox-form.tsx, apps/www/registry/default/example/date-picker-form.tsx, apps/www/registry/default/example/input-form.tsx, apps/www/registry/default/example/radio-group-form.tsx, apps/www/registry/default/example/select-form.tsx, apps/www/registry/default/example/switch-form.tsx, apps/www/registry/default/example/textarea-form.tsx, apps/www/registry/new-york/example/calendar-form.tsx, apps/www/registry/new-york/example/checkbox-form-multiple.tsx, apps/www/registry/new-york/example/checkbox-form-single.tsx, apps/www/registry/new-york/example/combobox-form.tsx, apps/www/registry/new-york/example/date-picker-form.tsx, apps/www/registry/new-york/example/input-form.tsx, apps/www/registry/new-york/example/radio-group-form.tsx, apps/www/registry/new-york/example/select-form.tsx, apps/www/registry/new-york/example/switch-form.tsx, apps/www/registry/new-york/example/textarea-form.tsx, apps/www/registry/schema.ts
As of v3 of zod, using `import * as z from "zod"` is no longer required, [see here](https://github.com/colinhacks/zod/blob/dd849254d1149bc1f2ef0f47f0f7607955e4db85/MIGRATION.md?plain=1#L30).
This PR aligns all zod imports to match `import { z } from "zod"`
Both methods are already used in the project.
This also aligns imports to match zod documentation.
=> refactor: update zod imports

apps/www/content/docs/installation/next.mdx
This PR fixes the issue [#2337](https://github.com/shadcn-ui/ui/issues/2377).
I removed `export` of `fontSans` from `app/layout.tsx`, which was causing a type error. 
I have ensured that this modification does not impact other functionalities. Your feedback on this pull request would be greatly appreciated.
Thank you for your consideration.
=> docs(next-installation): Fixed type error in Next.js installation by removing export from fontSans

apps/www/registry/default/block/dashboard-02.tsx, apps/www/registry/new-york/block/dashboard-02.tsx
Change link in the block `dashboard-02` from `"/"` to `"#"`.
As described in issue #3098
=> fix: dashboard-02 block (shadcn-ui#3098)

apps/www/registry/default/block/dashboard-03.tsx
This Pull Request fixes the misalignment between the aside and header borders in the default style for the dashboard-03 component of the blocks. It achieves alignment by adjusting the header height to match the aside border.
Before:
After:
=> fix(dashboard-3): align aside and header borders in default style

apps/www/lib/blocks.ts
FIXES : https://x.com/jimmeyer/status/1776487418150981661?s=46
The copy button in lift mode was copying code having imports as "@/registry/.../*.tsx" 
This PR replaces all the imports by "@/components/ui/*.tsx"
=> fix(blocks): replace code with @/components/ui imports while copying from lift-mode

apps/www/components/block-toolbar.tsx
When clicking on the "Lift Mode" Text instead of the toggle itself, since there were multiple `lift-mode` ids before (one for each block), the incorrect toggle would be activated.
https://github.com/shadcn-ui/ui/assets/61006057/261ec82f-9274-4e0a-ac21-5e3aa3ceece3
Instead of the id being static I changes the `id`, as well as the `htmlFor` attributes to `lift-mode-${block.name}`. This prevents duplicate ids, as long as there are no two blocks with the same name.
=> fix: :bug: lift mode duplicate ids lead to incorrect behavior

apps/www/content/docs/components/chart.mdx
docs: fix misspell of 'ChartTooltip'
=> docs: misspelled "ChartTooltip"

apps/www/content/docs/installation/vite.mdx
IDE uses the config mentioned in the `tsconfig.app.json` file whereas shadcn uses the config mentioned in the `tsconfig.json` file for path resolution 
Before adding the path to `tsconfig.app.json`
After adding the path to `tsconfig.app.json`
This commit mentions the same in the installation with `vite` docs
=> fix(docs): resolve imports for IDE

apps/www/app/(app)/colors/layout.tsx
The Tailwind CSS colors documentation link should be https://tailwindcss.com/docs/customizing-colors, rather than `/docs/components/chart`.
=> fix(docs): incorrect link to tailwindcss colors documentation

apps/www/content/docs/components/combobox.mdx
Just adding a missing `<Command>` that was missing from one of the docs examples.
=> docs: add missing command

apps/www/public/registry/index.json, apps/www/public/registry/styles/default/calendar.json, apps/www/public/registry/styles/new-york/calendar.json, apps/www/registry/ui.ts, packages/cli/package.json
This pins react-day-picker to v8 while we work on upgrading to v9. See #4371.
=> fix: pin react-day-picker

apps/www/content/docs/components/combobox.mdx
There is a misssing / for `Command`.
=> fix: missing close tag for command

apps/www/app/(app)/examples/mail/components/mail.tsx
content was overflowing horizontally on increasing the size of the 2rd column resizable component 
**We have a scroll bar at the bottom**
min width added to the 3rd column (mail preview)
=> fix: resizable mail component example, min width

apps/www/app/(app)/examples/dashboard/components/team-switcher.tsx, apps/www/app/(app)/examples/forms/account/account-form.tsx, apps/www/registry/default/example/combobox-demo.tsx, apps/www/registry/new-york/example/combobox-demo.tsx
Wrap CommandEmpty and CommandGroup inside CommandList 
Eliminated Error: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
=> fix(components): combobox: added command-list component to eliminate error

apps/www/app/(app)/examples/playground/components/model-selector.tsx
Issue: 
The ModelItem component's onPeek handler was sometimes logging incorrect data, causing the model selector to appear inconsistent.
Changes Made:
Verified that the aria-selected attribute is true before calling onPeek(model), ensuring the function is only called when the element is actually selected.
Fixed Model Selector Inconsistency in Playground Example
fixes #4506
=> fix: Playground example model selector working

apps/www/content/docs/components/toast.mdx
This pull request addresses a documentation error found in the ShadCN website's Toast component example. Specifically, the import route for the hook is incorrect in the example. and fixes [#4816](https://github.com/shadcn-ui/ui/issues/4816)
Upon reviewing the [ShadCN Toast documentation](https://ui.shadcn.com/docs/components/toast), I found that the import path for the Toast component hook was wrongly mentioned as being located in the `components` folder. According to the `component.json` file, the correct location of the hook is within the `hooks` folder inside the main directory.
- Corrected the import path in the Toast component example from `components` to `hooks`, as per the `component.json` file structure.
**Before:**
```js
import { useToast } from "@/components/use-toast";
``` …
=> Fix Incorrect Hook Import Path in Toast Component Example in ShadCN Docs

.changeset/chilly-geckos-run.md, packages/cli/src/utils/get-project-info.ts
Fixes https://github.com/shadcn-ui/ui/issues/4689
- Updated getTailwindCssFile function to include .scss files when checking for Tailwind CSS configuration.
- This change ensures that .scss files are properly identified and handled, improving compatibility with projects using SCSS.
=> fix(cli): Ensure .scss files are considered in getTailwindCssFile

.changeset/clever-swans-tan.md, packages/shadcn/src/utils/updaters/update-files.ts, packages/shadcn/test/utils/updaters/update-files.test.ts
Adding support for a `~/` prefix in the `target` specification of a block file so that you can specify files relative to the root of the project regardless of whether the project is `src` based or not.
=> Adding support for ~ in target specification

.changeset/hip-ads-destroy.md, packages/shadcn/src/utils/updaters/update-css-vars.ts, packages/shadcn/test/utils/schema/__snapshots__/registry-resolve-items-tree.test.ts.snap
after initializing nextjs project, the global css is 
after initializing shadcn , the global css is
`--foreground`, `--background` of nextjs conflict with shadcn. nextjs will override shadcn.
Fix #4923
=> fix(shadcn):  default next styles are not completely cleared

.changeset/hip-moose-add.md, .github/workflows/prerelease.yml, packages/shadcn/src/utils/registry/index.ts, packages/shadcn/test/utils/schema/__snapshots__/registry-resolve-items-tree.test.ts.snap
=> feat(shadcn): recursively resolve registry dependencies

apps/www/content/docs/installation/remix.mdx
Importing `tailwind.css` is incorrect as it will treat that file as a CSS Module, throwing that it has no `default` export. 
Instead, the tutorial relies on the import returning a _URL_ to the stylesheet. Adding `?url` to the import specifier is the way to go.
=> use "?url" suffix in "tailwind.css" import (Remix)

.changeset/rare-bugs-repair.md, packages/shadcn/src/commands/add.ts, packages/shadcn/src/utils/get-config.ts
This PR fixes the typo in the error message where the CLI tells the user to create a `component.json` file (singular), instead of a `components.json` file (plural).
Currently, the error message for not having a `components.json` file reads:
> ✔ You need to create a component.json file to add components. Proceed?
But, I believe it should be `components.json` (not `component.json`).
I also found another place in the get-cofing file where `components.json` is referenced as `component.json`, so included it in this PR.
Hope this helps 🤞
=> fix: Fix the typo in error messages (`component.json` → `components.json`)

apps/www/content/docs/components/sidebar.mdx
=> docs: fix prop name

apps/www/content/docs/components/sidebar.mdx
This PR intends to fix minor typo in the `sidebar` documentation.
=> docs(sidebar): fix typo in sidebar documentation

apps/www/content/docs/components/sidebar.mdx
**Issue:** When adding the sidebar component manually to an existing project, the sidebar styles are not applied.
**Cause:** The current setup guide for sidebar components is missing the step to add the sidebar config in to `tailwind.config.js`
**Solution:** I've added the step in the sidebar documentation explaining how to activate sidebar related styles utilities
=> docs: [Sidebar Component] add missing installation step in the sidebar component documentation

.changeset/friendly-mangos-fetch.md, packages/shadcn/src/utils/transformers/transform-rsc.ts, packages/shadcn/test/utils/__snapshots__/transform-rsc.test.ts.snap, packages/shadcn/test/utils/transform-rsc.test.ts
For external registry files that use single quote formatting, the `'use client'` directive will not be removed for projects with `rsc: false` configured due to the `transformRsc` util
This PR updates the equality check to a regex to fix this use case
https://codesandbox.io/p/devbox/dark-hill-lht8mm
1. Run `pnpx shadcn@latest add http://localhost:3000/registry/custom-button.json`
2. Output `custom-button.tsx` will still have the directive even though `rsc` is set to `false` in the `components.json`
=> fix(shadcn): fix transformRsc to account for '

apps/www/content/docs/installation/next.mdx
Updated broken link in documentation routing file. 
This ensures that the correct content is loaded based on the slug.
=> fix(docs): resolve link issue in documentation pages

apps/www/content/docs/cli.mdx
I updated the `cli.mdx` file and added `--all` option to the add command in the docs.
=> Add `--all` option to add command in cli docs

apps/www/components/mobile-nav.tsx
There were some svg warnings while running the apps/www regarding using not using camelCase in main-nav.tsx
=> fix: svg props casing to camelCase

apps/www/components/block-viewer.tsx
This pull request fixes an issue in the Shadcn website where copying the block component did not include the component's name. The update ensures that the name is now properly copied along with the rest of the component data.
Whenever the block got copied it exclude the block name. 
For example if you copy any block it will only give you `npx shadcn@latest add ` it will skip the name of the block.
=> fix: ensure block component name is copied in shadcn

packages/shadcn/test/utils/schema/__snapshots__/registry-resolve-items-tree.test.ts.snap
Updated snapshot components to use `React.ComponentProps` instead of custom interfaces for `input` and `Dialog` components. This simplifies the code by leveraging built-in React types, ensuring consistency and reducing potential errors arising from custom definitions.
=> test(snapshots): update input & command for consistency

CONTRIBUTING.md
Introduce a detailed workflow for running the CLI locally, ensuring contributors can easily test and develop enhancements in their local environment. This addition helps maintain consistency between CLI and component updates.
@shadcn LMK if we want to make more of an effort to callout/refactor the old cli instructions vs the new?
=> docs(contributing): add CLI usage instructions

.changeset/swift-eyes-dress.md, apps/www/lib/registry.ts, apps/www/public/registry.json, apps/www/public/schema/registry-item.json, packages/shadcn/src/registry/schema.ts, packages/shadcn/test/utils/updaters/update-files.test.ts
- introduce a new `registry:file` type
- makes `target` required for `registry:file` and `registry:page` types.
=> feat(shadcn): add new registry:file type

.changeset/spotty-plants-juggle.md, apps/www/content/docs/installation/tanstack.mdx, packages/shadcn/src/utils/get-project-info.ts
I tried the shadcn tanstack start guide with tailwindcss v4. Found two issues. One was incorrect paths in tsconfig and another being tanstack start is not detected if it is present as dev dependency. Fixed those.
=> fix(tanstack): fix paths value in tsconfig and check for tanstack start in devDeps also 

apps/www/public/r/colors/gray.json, apps/www/public/r/colors/neutral.json, apps/www/public/r/colors/slate.json, apps/www/public/r/colors/stone.json, apps/www/public/r/colors/zinc.json, apps/www/registry/registry-base-colors.ts
Remove excess semicolon in `--radius` variable, which will fix invalid generated css 
Fix #6737
=> fix(www): extra semicolon of --radius (#6737)

.changeset/metal-queens-hang.md, packages/shadcn/src/commands/add.ts, packages/shadcn/src/commands/init.ts, packages/shadcn/src/utils/create-project.test.ts, packages/shadcn/src/utils/create-project.ts
adds a new `--template` flag to the init command.
```
npx shadcn@latest init --template=next
```
```
npx shadcn@latest init --template=next-monorepo
```
=> feat(shadcn): add --template flag

.changeset/curly-impalas-give.md, packages/shadcn/src/utils/updaters/update-dependencies.ts
This change honors the silent flag by setting `--force` if `--silent` is on and components are being added to a React 19 project using `npm`.
=> fix: allow silent mode with npm on React 19

apps/www/components/code-block-command.tsx
fixes this:
(in <https://ui.shadcn.com/docs/installation/tanstack-router>)
after:
=> fix(www): code block command overflow

apps/www/content/docs/changelog.mdx, apps/www/content/docs/installation/gatsby.mdx, apps/www/content/docs/installation/react-router.mdx, apps/www/content/docs/installation/remix.mdx
Replaces mentions in the doc of the `shadcn-ui` deprecated package to `shadcn`
=> chore(www): replace shadcn-ui deprecated mentions to shadcn

templates/monorepo-next/.vscode/settings.json
Fixes an issue where Tailwind CSS IntelliSense wouldn't work in app folders (`/apps/web`, etc.) when using the default `shadcn/turborepo` setup.
By default, the VS Code Tailwind extension only detects the config inside `packages/ui`, causing class suggestions to fail in other packages.
This PR adds a `.vscode/settings.json` file that explicitly points to the correct config file:
```json
{
"tailwindCSS.experimental.configFile": "packages/ui/src/styles/globals.css"
}
```
I raised the issue here on Twitter:
🔗 [https://x.com/steellgold/status/1934295365760512388](https://x.com/steellgold/status/1934295365760512388)
It was solved thanks to this suggestion:
💡 [https://x.com/Mahmut\_Jomaa/status/1934316610719830421](https://x.com/Mahmut_Jomaa/status/1934316610719830421)
=> chore(vscode): configure Tailwind IntelliSense for monorepo UI

apps/v4/content/docs/(root)/figma.mdx
Adds link to [Obra shadcn/ui](https://www.figma.com/community/file/1514746685758799870/obra-shadcn-ui) by [Obra Studio](https://obra.studio/), now in v4 part.
=> docs(v4): link to obra figma kit

.claude/settings.local.json, packages/shadcn/src/registry/utils.test.ts, packages/shadcn/src/registry/utils.ts
We should only consider `registry:type === file` for universal components since this is the only type that would work without a framework and tsconfig.
=> fix(shadcn): universal item files type

.changeset/hip-pianos-fry.md, packages/shadcn/src/utils/transformers/transform-css-vars.ts, packages/shadcn/test/utils/__snapshots__/transform-css-vars.test.ts.snap, packages/shadcn/test/utils/__snapshots__/transform-tw-prefix.test.ts.snap
This fixes a bug in the transformCssVars transformer (when `tailwind.cssVariables: false`) that was rewriting all string literals in a file.
As a result, some strings ended up with nested quotes, for example:
```ts
import React from "'react'"
const icon = "'suffix'"
```
instead of staying untouched.
See #8185.
**Cause**
`transformCssVars` was rewriting all string literals using raw text APIs:
- it read strings with `getText()` (which includes the surrounding quotes),
- then wrote them back with `replaceWithText(...)` (adding quotes again).
When the mapping was a no-op (e.g., for non-class strings like import specifiers), this produced nested quotes.
**Fix**
Use literal-safe APIs:
- read with `getLiteralText()` (value without quotes),
- write with `setLiteralValue(...)` (ts-morph handles …
=> feat(shadcn): fix transformCssVars function

apps/v4/content/docs/registry/examples.mdx
| Before | After |
|--------|--------|
| ![](https://github.com/user-attachments/assets/ddcba004-21da-4f17-8880-904d4201939e) | ![](https://github.com/user-attachments/assets/e12ec13a-5cc5-41d0-bdda-972caf6f5fa2) |
=> fix: correct improper JSON syntax

apps/v4/registry/new-york-v4/examples/empty-demo.tsx
in the demo of empty component we got a misalignment between "Create Project" and "Import project" due to `size="sm"`.
=> correct alignment in empty component demo
