shadcn-ui/ui

README.md

My first ever github contribution! Hopefully I did it correctly...
- Class merging with `tailwind-merge`  - FIXED TYPO HERE (taiwind-merge - tailwind-merge)

Update README.md (Small typo)

---

apps/www/components/ui/dropdown-menu.tsx
templates/next-template/components/ui/dropdown-menu.tsx

Text + Border Color changes

---

apps/www/components/examples/navigation-menu/demo.tsx
apps/www/components/ui/navigation-menu.tsx

[Screencast from 02-06-2023 01:01:04 AM.webm](https://user-images.githubusercontent.com/78354432/216850993-9e2a87cb-c032-49a4-b2bd-18fd3b6f65ba.webm)

fix: broken navigation menu in small screen, #40

---

apps/www/components/ui/button.tsx
examples/playground/components/ui/button.tsx
templates/next-template/components/ui/button.tsx

Added Tailwind class `active:scale-95` on Button component, to provide feedback on click / tap

fix: buttons added scale down on click/tap

---

apps/www/hooks/use-toast.ts

Add code block to case which declares a variable

Unexpected lexical declaration in case block

---

examples/playground/components/preset-save.tsx

This fix resolves an issue mentioned in #83.

fix(example/playground): save preset input value

---

apps/www/content/docs/primitives/sheet.mdx

This PR changes the wrong import of the sheet component

docs: change wrong import

---

apps/www/components/component-example.tsx

Changed codeString to accept the rawString from the component if the value isn't available before returning null.
Fixes #219

fix: component selection in copy-button

---

.changeset/purple-dryers-repeat.md
apps/www/content/docs/installation.mdx
packages/cli/src/utils/templates.ts

fix(shadcn-ui): update color of cards in dark mode

---

templates/next-template/tsconfig.json

#8 Now enables strict type checking in the template

strict-typechecking-in-template

---

apps/www/app/examples/forms/account/account-form.tsx

Display account form name input error

---

apps/www/components/react-hook-form/form.tsx

Avoid unnecessary state subscriptions

---

apps/www/app/examples/forms/account/account-form.tsx
apps/www/app/examples/forms/appearance/appearance-form.tsx
apps/www/app/examples/forms/profile-form.tsx
apps/www/components/examples/input/react-hook-form.tsx
apps/www/components/examples/textarea/react-hook-form.tsx
apps/www/content/docs/forms/react-hook-form.mdx

- Update controlled inputs examples
- Update form usage docs example
Closes: #384

Refactor controlled inputs API examples

---

apps/www/content/docs/forms/react-hook-form.mdx

Following discussion [here](https://github.com/shadcn/ui/issues/410).
Please feel free to ask me to change anything, or to make any change yourself in this PR.
Thanks for your work :slightly_smiling_face:

Fix inconsistency in forms docs + add note about uncontrolled components

---

apps/www/content/docs/changelog.mdx

Changes `'use client' directory` to `'use client' directive` , which I believe is the intent.

fix(changelog): directory -> directive

---

apps/www/content/docs/components/skeleton.mdx

fix(docs): remove duplicate install command

---

apps/www/config/docs.ts
apps/www/content/docs/installation/gatsby.mdx
apps/www/content/docs/installation/index.mdx

docs: add installation guide for Gatsby

---

apps/www/app/docs/[[...slug]]/page.tsx

Fixes #1049 
Adds scrollbar which will make the overflow content available to the user

Address overflow issue in documentation

---

apps/www/app/examples/cards/page.tsx

Thank you Jony_David https://twitter.com/Jony_David/status/1685003252104855552

fix(www): responsive cards

---

apps/www/app/examples/cards/components/payment-method.tsx
apps/www/registry/default/example/cards/payment-method.tsx
apps/www/registry/new-york/example/cards/payment-method.tsx

The `:has` selector is not working on Firefox, I added a new class using the `peer` variant.

fix(www): payment method :has selector not working on Firefox

---

CONTRIBUTING.md
apps/www/content/docs/dark-mode/next.mdx

docs: update contrubuting.md and next.mdx

---

apps/www/content/docs/cli.mdx

Updated the help text for choosing all components with add command

docs(cli): update docs for add [components] - select all compoents help text

---

.changeset/hot-comics-smell.md
packages/cli/src/commands/add.ts

example for [use-toast.ts](https://github.com/shadcn-ui/ui/blob/main/apps/www/registry/default/ui/use-toast.ts) file

Change file extension correctly for typescript files

---

apps/www/registry/default/ui/table.tsx
apps/www/registry/new-york/ui/table.tsx

Replacement of #428 as there is a change in the directory structure
closes #416

fix(www): table overflow

---

apps/www/content/docs/components/combobox.mdx
apps/www/registry/default/example/combobox-demo.tsx
apps/www/registry/default/example/combobox-dropdown-menu.tsx
apps/www/registry/default/example/combobox-popover.tsx
apps/www/registry/new-york/example/combobox-demo.tsx
apps/www/registry/new-york/example/combobox-dropdown-menu.tsx
apps/www/registry/new-york/example/combobox-popover.tsx

Fix combobox examples using labels as value

---

apps/www/registry/default/example/card-demo.tsx
apps/www/registry/new-york/example/card-demo.tsx

docs(card): remove unused line #1652

---

.github/workflows/code-check.yml
.github/workflows/test.yml

This PR updates the workflow jobs name to make debugging easier.

ci: update tasks name to make debug easier

---

apps/www/registry/default/ui/alert-dialog.tsx

fix(module): removed unused children prop from alert-dialog

---

CONTRIBUTING.md

Added detailed info to clone and setup the project to contribute.
Following the PR #1650 and suggestion of @shadcn.  Thanks!

docs: updated contributing guidelines to easily contribute

---

apps/www/app/examples/tasks/components/columns.tsx
apps/www/content/docs/components/data-table.mdx
apps/www/registry/default/example/cards/data-table.tsx
apps/www/registry/default/example/data-table-demo.tsx
apps/www/registry/new-york/example/cards/data-table.tsx
apps/www/registry/new-york/example/data-table-demo.tsx

add indeterminate state checkboxes on all data table demos and code examples

docs(components): add indeterminate state checkboxes 

---

apps/www/registry/default/example/cards/metric.tsx
apps/www/registry/new-york/example/cards/metric.tsx

fix(#1969): typo in metric cards

---

apps/www/app/examples/mail/components/mail-display.tsx

Fixes #2277
Add `e.preventDefault()` to prevent page reload in mail component

Fix: Add e.preventDefault() to prevent page reload

---

apps/www/content/docs/installation/next.mdx

New Line added to the docs.
Just for the consistency.

[Docs] Update CLI options while configuring `components.json`

---

.changeset/wet-eagles-leave.md
packages/cli/src/commands/add.ts
packages/cli/src/commands/diff.ts
packages/cli/src/commands/init.ts
packages/cli/src/utils/get-config.ts
packages/cli/src/utils/registry/index.ts
packages/cli/src/utils/registry/schema.ts
packages/cli/src/utils/transformers/index.ts
packages/cli/src/utils/transformers/transform-css-vars.ts

refactor: update zod imports in /cli

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

[Feat]: Add Bug report and Feature request templates

---

apps/www/content/docs/installation/next.mdx

Fixes import in the Next.js onboarding instructions

fix nextjs docs

---

apps/www/package.json
pnpm-lock.yaml

chore(vaul): upgrade vaul version to a more recent

---

apps/www/app/(app)/colors/layout.tsx
apps/www/app/(app)/colors/page.tsx
apps/www/components/color-format-selector.tsx
apps/www/components/color-palette.tsx
apps/www/components/color.tsx
apps/www/components/main-nav.tsx
apps/www/config/docs.ts
apps/www/hooks/use-colors.ts
apps/www/hooks/use-copy-to-clipboard.ts
apps/www/lib/colors.ts
apps/www/lib/events.ts

for quick copy/paste in all formats

feat: add colors page

---

apps/www/components/theme-customizer.tsx

Typo fix to get proper value when pressing copy code in theme customizer section.
Link for Issue: https://github.com/shadcn-ui/ui/issues/4314

fix: typo in theme template causing blank color values.

---

apps/www/content/docs/components/data-table.mdx

Hi,
Remove the `MoreHorizontal` import from sorting section' codeblock, as it is not being used :)

fix(www): remove unused import

---

packages/shadcn/src/utils/get-project-info.ts

Added scss support for shadcn package (v2)

fix(shadcn): Ensure .scss files are considered in init command

---

.changeset/wise-cheetahs-report.md
packages/shadcn/src/utils/transformers/transform-tw-prefix.ts
packages/shadcn/test/utils/__snapshots__/transform-tw-prefix.test.ts.snap
packages/shadcn/test/utils/schema/__snapshots__/registry-resolve-items-tree.test.ts.snap
packages/shadcn/test/utils/transform-tw-prefix.test.ts

support tw prefixes for registry files with single quote formatting

fix(shadcn): Support single quote formatted registry files (fixes #4870)

---

apps/www/content/docs/components/sidebar.mdx

Small typo error on sidebar.mdx

docs: fix type in sidebar.mdx

---

.changeset/config.json
.changeset/fifty-rabbits-beg.md
packages/shadcn/src/utils/create-project.ts
pnpm-lock.yaml

Keeping an eye on https://github.com/radix-ui/icons/pull/184

fix(shadcn): temporarily pin create-next-app

---

.changeset/calm-bees-train.md
apps/www/content/docs/components/chart.mdx
apps/www/content/docs/react-19.mdx
packages/shadcn/src/utils/updaters/update-dependencies.ts

I (unfortunately) need to bring this back (at least for a few more days)

Revert "feat: remove npm flags"

---

apps/www/app/(app)/blocks/layout.tsx
apps/www/components/announcement.tsx
apps/www/config/docs.ts
apps/www/content/docs/blocks.mdx

We’re inviting the community to contribute to the blocks library. 🎉

docs(www): add blocks contribution docs

---

.changeset/new-cheetahs-dance.md
packages/shadcn/src/commands/init.ts
packages/shadcn/src/registry/api.ts
packages/shadcn/src/utils/get-project-info.ts
packages/shadcn/src/utils/updaters/update-css-vars.ts
packages/shadcn/test/utils/updaters/update-css-vars.test.ts

For new v4 projects, we'll automatically set the style to `new-york`.

(8/n) shadcn: default to new-york for v4

---

apps/v4/components/app-sidebar.tsx
apps/v4/components/combobox-demo.tsx

feat(v4): add combobox with checkbox example

---

apps/www/registry/new-york/blocks/sidebar-16/components/site-header.tsx

Fixed a small typo in the site-header.tsx

docs(www): fix typo in site-header.tsx

---

apps/v4/registry.json
apps/v4/scripts/build-registry.mts
apps/www/public/r/styles/new-york-v4/accordion.json
apps/www/public/r/styles/new-york-v4/index.json

This should be merged after https://github.com/shadcn-ui/ui/pull/7228

fix: move tw-animate-css to devDependencies

---

.changeset/eight-olives-shop.md
packages/shadcn/src/migrations/migrate-radix.test.ts
packages/shadcn/src/migrations/migrate-radix.ts

See https://x.com/rampartsRVP/status/1932821683938762912

fix(shadcn): semicolon in code style

---

.changeset/fifty-gifts-perform.md
apps/v4/content/docs/(root)/cli.mdx
packages/shadcn/src/commands/add.ts
packages/shadcn/src/commands/init.ts
packages/shadcn/src/registry/api.test.ts
packages/shadcn/src/registry/api.ts
packages/shadcn/src/registry/utils.test.ts
packages/shadcn/src/registry/utils.ts

`npx shadcn init ./path/to/local/file.json` or `npx shadcn add ./path/to/local/file.json`

feat(shadcn): add file support

---

apps/v4/content/docs/registry/getting-started.mdx

Corrected the link to the namespaced registries documentation.

Docs: Fix link to namespaced registries documentation

---

apps/v4/public/r/registries.json

This PR adds **@smoothui** to the list of trusted registries.
**SmoothUI** is a library of ready-to-use UI components built with **React, TailwindCSS, and Framer Motion**, focused on providing microinteractions and polished UI experiences. It’s designed to be easily copied, pasted, and integrated into projects, fitting naturally into the shadcn/ui ecosystem.
- Added `@smoothui` to the trusted registries list.
Developers using shadcn/ui often look for high-quality component libraries that complement the design system. By including SmoothUI in the trusted registries, users will have access to animated, interactive components that can enhance their applications while maintaining consistency with shadcn/ui.
- [SmoothUI website](https://smoothui.dev)

feat: add @smoothui to trusted registries

---

apps/v4/public/r/registries.json

This PR adds @elements to the list of trusted registries.
Elements is an open-source registry of full-stack components for modern web apps. It goes beyond UI by providing complete integrations (auth, payments, AI, jobs, files, database) built with React, TypeScript, and TailwindCSS. Each component is designed to be installed in seconds and tweaked easily, fitting naturally into the shadcn/ui ecosystem.
Developers using shadcn/ui often need more than static UI, they need production-ready flows and integrations. By including Elements in the trusted registries, users get access to full-stack, end-to-end components that speed up shipping without sacrificing design or developer experience.
It’s the next logical step of the @shadcn/ui ecosystem.
website: https://www.tryelements.dev/
github: …

feat: add @elements to trusted registries

---

apps/v4/public/r/registries.json

This PR adds Animate UI to the list of trusted registries.
Links:
- website: [https://animate-ui.com](https://animate-ui.com)
- x: [https://x.com/animate_ui](https://x.com/animate_ui)

feat(v4): add @animate-ui to trusted registries

---

apps/v4/public/r/registries.json

Description
This PR adds @skiper-ui to the list of trusted registries.
Changes
Added @skiper-ui to the trusted registries list.
References
[Skiper-UI](https://skiper-ui.com/) website

feat: add @skiper-ui to trusted registries

---

apps/v4/public/r/registries.json

rename from `@magic-ui` to `@magicui`

fix: update magicui registry name

---

apps/v4/content/docs/(root)/figma.mdx
apps/v4/public/r/registries.json
apps/www/content/docs/figma.mdx

This PR adds
* [@tweakcn](https://tweakcn.com) to trusted registries
* [shadcraft](https://shadcraft.com) - a figma kit for shadcn/ui to the Figma docs

Add @tweakcn to trusted registries & Add shadcraft to Figma docs

---

apps/v4/public/r/registries.json

This PR adds @assistant-ui namespace to `registries.json`

feat: add @assistant-ui to trusted registries

---

apps/v4/public/r/registries.json

Components: [bucharitesh.in/craft](https://bucharitesh.in/craft)

feat: add @bucharitesh in trusted registries

---

apps/v4/public/r/registries.json

This PR adds [Better Upload](https://better-upload.com) to the trusted registries.

feat: add @better-upload to trusted registries

---

apps/v4/public/r/registries.json

A map component based on shadcn/ui and Leaflet: https://shadcn-map.vercel.app

feat: add @shadcn-map to the registry
